8 footer
GSG-G10/Watch-Store pull request #21
Opened 2021-07-13 15:13 UTC by rawand1998

here we add the footer to home page and made style for it.

2021-07-13 15:29 UTC, Mu7ammadAbed requested changes

2021-07-13 15:29 UTC, Mu7ammadAbed commented on index.html
> +          <img src="logo2.jpg" alt="" />
Add a real descriptive image alternative

2021-07-13 15:29 UTC, Mu7ammadAbed commented on index.html
> +          <button>Contact Us</button>
If you want a button to redirect you to another page or section you can use anchor tag but don't use a button for redirection, if you want the shape and style of the button you can style the anchor to look like a button by css but not using a button.

2021-07-13 15:29 UTC, Mu7ammadAbed commented on styles/home.css
> +footer {
If you want to select an html element to style it you should add a class name to it and select it by class name for multiple reasons, specificity is one of them.

2021-07-13 17:35 UTC, umarsalah requested changes

2021-07-13 17:35 UTC, umarsalah commented on index.html
> -        <img src="" alt="">
Add a real image src, we add a new logo photo.

2021-07-13 19:33 UTC, Mu7ammadAbed commented on styles/home.css
> +footer img {
The same as before here, just add a class name to the image and select it

2021-07-13 21:59 UTC, umarsalah approved these changes

2021-07-14 06:39 UTC, muath-khatib approved these changes

2021-07-14 07:26 UTC, Mu7ammadAbed approved these changes

2021-07-14 07:26 UTC, merged